[package]
name = "vlcb-defs"
version = "1.1.0"
edition = "2021"
rust-version = "1.71.0"
authors = [
    "Freja <me@freja.codes>"
]
homepage = "https://github.com/0xfrej/vlcb-defs-rs"
repository = "https://github.com/0xfrej/vlcb-defs-rs"
documentation = "https://docs.rs/vlcb-defs"
license = "Apache-2"
keywords = ["lcb", "vlcb", "cbus", "merg"]
exclude = ["/codegen"]

[dependencies]
num-traits = { version = "0.2", default-features = false, features = [] }
num_enum = { version = "0.7", default-features = false }
defmt = { version = "0.3", optional = true }

[features]
defmt = ["dep:defmt"]