[package]
name = "formatter"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "formatter"
path = "format.rs"

[dependencies]
anyhow = "1.0"
prettyplease = "0.2"
syn = { version = "2.0", default-features = false, features = ["parsing", "printing"] }